// Static fallback directory of DummyJSON users for instant offline display and zero-latency first render.
import 'package:angcla_advmobprog_longexam1/models/user.dart';

const Map<int, User> kDummyUsersFallback = {
  1: User(
    id: 1,
    firstName: 'Emily',
    lastName: 'Johnson',
    username: 'emilys',
    image: 'https://dummyjson.com/icon/emilys/128',
    email: '',
    gender: '',
  ),
  2: User(
    id: 2,
    firstName: 'Michael',
    lastName: 'Williams',
    username: 'michaelw',
    image: 'https://dummyjson.com/icon/michaelw/128',
    email: '',
    gender: '',
  ),
  3: User(
    id: 3,
    firstName: 'Sophia',
    lastName: 'Brown',
    username: 'sophiab',
    image: 'https://dummyjson.com/icon/sophiab/128',
    email: '',
    gender: '',
  ),
  4: User(
    id: 4,
    firstName: 'James',
    lastName: 'Davis',
    username: 'jamesd',
    image: 'https://dummyjson.com/icon/jamesd/128',
    email: '',
    gender: '',
  ),
  5: User(
    id: 5,
    firstName: 'Emma',
    lastName: 'Miller',
    username: 'emmaj',
    image: 'https://dummyjson.com/icon/emmaj/128',
    email: '',
    gender: '',
  ),
  6: User(
    id: 6,
    firstName: 'Olivia',
    lastName: 'Wilson',
    username: 'oliviaw',
    image: 'https://dummyjson.com/icon/oliviaw/128',
    email: '',
    gender: '',
  ),
  7: User(
    id: 7,
    firstName: 'Alexander',
    lastName: 'Jones',
    username: 'alexanderj',
    image: 'https://dummyjson.com/icon/alexanderj/128',
    email: '',
    gender: '',
  ),
  8: User(
    id: 8,
    firstName: 'Ava',
    lastName: 'Taylor',
    username: 'avat',
    image: 'https://dummyjson.com/icon/avat/128',
    email: '',
    gender: '',
  ),
  9: User(
    id: 9,
    firstName: 'Ethan',
    lastName: 'Martinez',
    username: 'ethanm',
    image: 'https://dummyjson.com/icon/ethanm/128',
    email: '',
    gender: '',
  ),
  10: User(
    id: 10,
    firstName: 'Isabella',
    lastName: 'Anderson',
    username: 'isabellad',
    image: 'https://dummyjson.com/icon/isabellad/128',
    email: '',
    gender: '',
  ),
  11: User(
    id: 11,
    firstName: 'Liam',
    lastName: 'Garcia',
    username: 'liamg',
    image: 'https://dummyjson.com/icon/liamg/128',
    email: '',
    gender: '',
  ),
  12: User(
    id: 12,
    firstName: 'Mia',
    lastName: 'Rodriguez',
    username: 'miar',
    image: 'https://dummyjson.com/icon/miar/128',
    email: '',
    gender: '',
  ),
  13: User(
    id: 13,
    firstName: 'Noah',
    lastName: 'Hernandez',
    username: 'noahh',
    image: 'https://dummyjson.com/icon/noahh/128',
    email: '',
    gender: '',
  ),
  14: User(
    id: 14,
    firstName: 'Charlotte',
    lastName: 'Lopez',
    username: 'charlottem',
    image: 'https://dummyjson.com/icon/charlottem/128',
    email: '',
    gender: '',
  ),
  15: User(
    id: 15,
    firstName: 'William',
    lastName: 'Gonzalez',
    username: 'williamg',
    image: 'https://dummyjson.com/icon/williamg/128',
    email: '',
    gender: '',
  ),
  16: User(
    id: 16,
    firstName: 'Avery',
    lastName: 'Perez',
    username: 'averyp',
    image: 'https://dummyjson.com/icon/averyp/128',
    email: '',
    gender: '',
  ),
  17: User(
    id: 17,
    firstName: 'Evelyn',
    lastName: 'Sanchez',
    username: 'evelyns',
    image: 'https://dummyjson.com/icon/evelyns/128',
    email: '',
    gender: '',
  ),
  18: User(
    id: 18,
    firstName: 'Logan',
    lastName: 'Torres',
    username: 'logant',
    image: 'https://dummyjson.com/icon/logant/128',
    email: '',
    gender: '',
  ),
  19: User(
    id: 19,
    firstName: 'Abigail',
    lastName: 'Rivera',
    username: 'abigailr',
    image: 'https://dummyjson.com/icon/abigailr/128',
    email: '',
    gender: '',
  ),
  20: User(
    id: 20,
    firstName: 'Jackson',
    lastName: 'Evans',
    username: 'jacksone',
    image: 'https://dummyjson.com/icon/jacksone/128',
    email: '',
    gender: '',
  ),
  21: User(
    id: 21,
    firstName: 'Madison',
    lastName: 'Collins',
    username: 'madisonc',
    image: 'https://dummyjson.com/icon/madisonc/128',
    email: '',
    gender: '',
  ),
  22: User(
    id: 22,
    firstName: 'Elijah',
    lastName: 'Stewart',
    username: 'elijahs',
    image: 'https://dummyjson.com/icon/elijahs/128',
    email: '',
    gender: '',
  ),
  23: User(
    id: 23,
    firstName: 'Chloe',
    lastName: 'Morales',
    username: 'chloem',
    image: 'https://dummyjson.com/icon/chloem/128',
    email: '',
    gender: '',
  ),
  24: User(
    id: 24,
    firstName: 'Mateo',
    lastName: 'Nguyen',
    username: 'mateon',
    image: 'https://dummyjson.com/icon/mateon/128',
    email: '',
    gender: '',
  ),
  25: User(
    id: 25,
    firstName: 'Harper',
    lastName: 'Kelly',
    username: 'harpere',
    image: 'https://dummyjson.com/icon/harpere/128',
    email: '',
    gender: '',
  ),
  26: User(
    id: 26,
    firstName: 'Evelyn',
    lastName: 'Gonzalez',
    username: 'evelyng',
    image: 'https://dummyjson.com/icon/evelyng/128',
    email: '',
    gender: '',
  ),
  27: User(
    id: 27,
    firstName: 'Daniel',
    lastName: 'Cook',
    username: 'danielc',
    image: 'https://dummyjson.com/icon/danielc/128',
    email: '',
    gender: '',
  ),
  28: User(
    id: 28,
    firstName: 'Lily',
    lastName: 'Lee',
    username: 'lilyb',
    image: 'https://dummyjson.com/icon/lilyb/128',
    email: '',
    gender: '',
  ),
  29: User(
    id: 29,
    firstName: 'Henry',
    lastName: 'Hill',
    username: 'henryh',
    image: 'https://dummyjson.com/icon/henryh/128',
    email: '',
    gender: '',
  ),
  30: User(
    id: 30,
    firstName: 'Addison',
    lastName: 'Wright',
    username: 'addisonw',
    image: 'https://dummyjson.com/icon/addisonw/128',
    email: '',
    gender: '',
  ),
  31: User(
    id: 31,
    firstName: 'Gabriel',
    lastName: 'Adams',
    username: 'gabriela',
    image: 'https://dummyjson.com/icon/gabriela/128',
    email: '',
    gender: '',
  ),
  32: User(
    id: 32,
    firstName: 'Natalie',
    lastName: 'Harris',
    username: 'natalieh',
    image: 'https://dummyjson.com/icon/natalieh/128',
    email: '',
    gender: '',
  ),
  33: User(
    id: 33,
    firstName: 'Carter',
    lastName: 'Baker',
    username: 'carterb',
    image: 'https://dummyjson.com/icon/carterb/128',
    email: '',
    gender: '',
  ),
  34: User(
    id: 34,
    firstName: 'Sofia',
    lastName: 'Mitchell',
    username: 'sofiam',
    image: 'https://dummyjson.com/icon/sofiam/128',
    email: '',
    gender: '',
  ),
  35: User(
    id: 35,
    firstName: 'Jack',
    lastName: 'Ward',
    username: 'jackw',
    image: 'https://dummyjson.com/icon/jackw/128',
    email: '',
    gender: '',
  ),
  36: User(
    id: 36,
    firstName: 'Harper',
    lastName: 'Turner',
    username: 'harpert',
    image: 'https://dummyjson.com/icon/harpert/128',
    email: '',
    gender: '',
  ),
  37: User(
    id: 37,
    firstName: 'Mason',
    lastName: 'Parker',
    username: 'masonp',
    image: 'https://dummyjson.com/icon/masonp/128',
    email: '',
    gender: '',
  ),
  38: User(
    id: 38,
    firstName: 'Aria',
    lastName: 'Roberts',
    username: 'ariar',
    image: 'https://dummyjson.com/icon/ariar/128',
    email: '',
    gender: '',
  ),
  39: User(
    id: 39,
    firstName: 'Lucas',
    lastName: 'Gray',
    username: 'lucasg',
    image: 'https://dummyjson.com/icon/lucasg/128',
    email: '',
    gender: '',
  ),
  40: User(
    id: 40,
    firstName: 'Ella',
    lastName: 'Adams',
    username: 'ellaa',
    image: 'https://dummyjson.com/icon/ellaa/128',
    email: '',
    gender: '',
  ),
  41: User(
    id: 41,
    firstName: 'Evan',
    lastName: 'Reed',
    username: 'evanr',
    image: 'https://dummyjson.com/icon/evanr/128',
    email: '',
    gender: '',
  ),
  42: User(
    id: 42,
    firstName: 'Avery',
    lastName: 'Carter',
    username: 'averyc',
    image: 'https://dummyjson.com/icon/averyc/128',
    email: '',
    gender: '',
  ),
  43: User(
    id: 43,
    firstName: 'Benjamin',
    lastName: 'Foster',
    username: 'benjaminf',
    image: 'https://dummyjson.com/icon/benjaminf/128',
    email: '',
    gender: '',
  ),
  44: User(
    id: 44,
    firstName: 'Scarlett',
    lastName: 'Wright',
    username: 'scarlettw',
    image: 'https://dummyjson.com/icon/scarlettw/128',
    email: '',
    gender: '',
  ),
  45: User(
    id: 45,
    firstName: 'Lincoln',
    lastName: 'Kelly',
    username: 'lincolnk',
    image: 'https://dummyjson.com/icon/lincolnk/128',
    email: '',
    gender: '',
  ),
  46: User(
    id: 46,
    firstName: 'Hannah',
    lastName: 'Robinson',
    username: 'hannahr',
    image: 'https://dummyjson.com/icon/hannahr/128',
    email: '',
    gender: '',
  ),
  47: User(
    id: 47,
    firstName: 'Nicholas',
    lastName: 'Bailey',
    username: 'nicholasb',
    image: 'https://dummyjson.com/icon/nicholasb/128',
    email: '',
    gender: '',
  ),
  48: User(
    id: 48,
    firstName: 'Luna',
    lastName: 'Russell',
    username: 'lunar',
    image: 'https://dummyjson.com/icon/lunar/128',
    email: '',
    gender: '',
  ),
  49: User(
    id: 49,
    firstName: 'Jacob',
    lastName: 'Cooper',
    username: 'jacobc',
    image: 'https://dummyjson.com/icon/jacobc/128',
    email: '',
    gender: '',
  ),
  50: User(
    id: 50,
    firstName: 'Stella',
    lastName: 'Hughes',
    username: 'stellah',
    image: 'https://dummyjson.com/icon/stellah/128',
    email: '',
    gender: '',
  ),
  51: User(
    id: 51,
    firstName: 'Eli',
    lastName: 'Bennett',
    username: 'elib',
    image: 'https://dummyjson.com/icon/elib/128',
    email: '',
    gender: '',
  ),
  52: User(
    id: 52,
    firstName: 'Grace',
    lastName: 'Perry',
    username: 'gracep',
    image: 'https://dummyjson.com/icon/gracep/128',
    email: '',
    gender: '',
  ),
  53: User(
    id: 53,
    firstName: 'Lucas',
    lastName: 'Gordon',
    username: 'lucasgx',
    image: 'https://dummyjson.com/icon/lucasgx/128',
    email: '',
    gender: '',
  ),
  54: User(
    id: 54,
    firstName: 'Ava',
    lastName: 'Harrison',
    username: 'avah',
    image: 'https://dummyjson.com/icon/avah/128',
    email: '',
    gender: '',
  ),
  55: User(
    id: 55,
    firstName: 'Owen',
    lastName: 'Fisher',
    username: 'owenf',
    image: 'https://dummyjson.com/icon/owenf/128',
    email: '',
    gender: '',
  ),
  56: User(
    id: 56,
    firstName: 'Samantha',
    lastName: 'Howard',
    username: 'samanthah',
    image: 'https://dummyjson.com/icon/samanthah/128',
    email: '',
    gender: '',
  ),
  57: User(
    id: 57,
    firstName: 'Nathan',
    lastName: 'Dixon',
    username: 'nathand',
    image: 'https://dummyjson.com/icon/nathand/128',
    email: '',
    gender: '',
  ),
  58: User(
    id: 58,
    firstName: 'Bella',
    lastName: 'Grant',
    username: 'bellag',
    image: 'https://dummyjson.com/icon/bellag/128',
    email: '',
    gender: '',
  ),
  59: User(
    id: 59,
    firstName: 'Ethan',
    lastName: 'Fletcher',
    username: 'ethanf',
    image: 'https://dummyjson.com/icon/ethanf/128',
    email: '',
    gender: '',
  ),
  60: User(
    id: 60,
    firstName: 'Lillian',
    lastName: 'Simmons',
    username: 'lillians',
    image: 'https://dummyjson.com/icon/lillians/128',
    email: '',
    gender: '',
  ),
  61: User(
    id: 61,
    firstName: 'Mason',
    lastName: 'Pearson',
    username: 'masonpx',
    image: 'https://dummyjson.com/icon/masonpx/128',
    email: '',
    gender: '',
  ),
  62: User(
    id: 62,
    firstName: 'Leah',
    lastName: 'Henderson',
    username: 'leahh',
    image: 'https://dummyjson.com/icon/leahh/128',
    email: '',
    gender: '',
  ),
  63: User(
    id: 63,
    firstName: 'Logan',
    lastName: 'Lawson',
    username: 'loganl',
    image: 'https://dummyjson.com/icon/loganl/128',
    email: '',
    gender: '',
  ),
  64: User(
    id: 64,
    firstName: 'Avery',
    lastName: 'Barnes',
    username: 'averyb',
    image: 'https://dummyjson.com/icon/averyb/128',
    email: '',
    gender: '',
  ),
  65: User(
    id: 65,
    firstName: 'Caleb',
    lastName: 'Perkins',
    username: 'calebp',
    image: 'https://dummyjson.com/icon/calebp/128',
    email: '',
    gender: '',
  ),
  66: User(
    id: 66,
    firstName: 'Aria',
    lastName: 'Ferguson',
    username: 'ariaf',
    image: 'https://dummyjson.com/icon/ariaf/128',
    email: '',
    gender: '',
  ),
  67: User(
    id: 67,
    firstName: 'Gabriel',
    lastName: 'Hayes',
    username: 'gabrielh',
    image: 'https://dummyjson.com/icon/gabrielh/128',
    email: '',
    gender: '',
  ),
  68: User(
    id: 68,
    firstName: 'Layla',
    lastName: 'Sullivan',
    username: 'laylas',
    image: 'https://dummyjson.com/icon/laylas/128',
    email: '',
    gender: '',
  ),
  69: User(
    id: 69,
    firstName: 'Christopher',
    lastName: 'West',
    username: 'christopherw',
    image: 'https://dummyjson.com/icon/christopherw/128',
    email: '',
    gender: '',
  ),
  70: User(
    id: 70,
    firstName: 'Zoe',
    lastName: 'Nicholson',
    username: 'zoen',
    image: 'https://dummyjson.com/icon/zoen/128',
    email: '',
    gender: '',
  ),
  71: User(
    id: 71,
    firstName: 'Nolan',
    lastName: 'Bryant',
    username: 'nolanb',
    image: 'https://dummyjson.com/icon/nolanb/128',
    email: '',
    gender: '',
  ),
  72: User(
    id: 72,
    firstName: 'Victoria',
    lastName: 'McDonald',
    username: 'victoriam',
    image: 'https://dummyjson.com/icon/victoriam/128',
    email: '',
    gender: '',
  ),
  73: User(
    id: 73,
    firstName: 'Max',
    lastName: 'Russell',
    username: 'maxr',
    image: 'https://dummyjson.com/icon/maxr/128',
    email: '',
    gender: '',
  ),
  74: User(
    id: 74,
    firstName: 'Penelope',
    lastName: 'Harper',
    username: 'penelopeh',
    image: 'https://dummyjson.com/icon/penelopeh/128',
    email: '',
    gender: '',
  ),
  75: User(
    id: 75,
    firstName: 'Ryan',
    lastName: 'Graham',
    username: 'ryang',
    image: 'https://dummyjson.com/icon/ryang/128',
    email: '',
    gender: '',
  ),
  76: User(
    id: 76,
    firstName: 'Madeline',
    lastName: 'Simpson',
    username: 'madelines',
    image: 'https://dummyjson.com/icon/madelines/128',
    email: '',
    gender: '',
  ),
  77: User(
    id: 77,
    firstName: 'Jonathan',
    lastName: 'Pierce',
    username: 'jonathanp',
    image: 'https://dummyjson.com/icon/jonathanp/128',
    email: '',
    gender: '',
  ),
  78: User(
    id: 78,
    firstName: 'Eleanor',
    lastName: 'Tyler',
    username: 'eleanort',
    image: 'https://dummyjson.com/icon/eleanort/128',
    email: '',
    gender: '',
  ),
  79: User(
    id: 79,
    firstName: 'Isaac',
    lastName: 'Lawrence',
    username: 'isaacl',
    image: 'https://dummyjson.com/icon/isaacl/128',
    email: '',
    gender: '',
  ),
  80: User(
    id: 80,
    firstName: 'Hazel',
    lastName: 'Gardner',
    username: 'hazelg',
    image: 'https://dummyjson.com/icon/hazelg/128',
    email: '',
    gender: '',
  ),
  81: User(
    id: 81,
    firstName: 'Austin',
    lastName: 'Hudson',
    username: 'austinh',
    image: 'https://dummyjson.com/icon/austinh/128',
    email: '',
    gender: '',
  ),
  82: User(
    id: 82,
    firstName: 'Lillian',
    lastName: 'Bishop',
    username: 'lillianb',
    image: 'https://dummyjson.com/icon/lillianb/128',
    email: '',
    gender: '',
  ),
  83: User(
    id: 83,
    firstName: 'Dylan',
    lastName: 'Wells',
    username: 'dylanw',
    image: 'https://dummyjson.com/icon/dylanw/128',
    email: '',
    gender: '',
  ),
  84: User(
    id: 84,
    firstName: 'Aaliyah',
    lastName: 'Hanson',
    username: 'aaliyahh',
    image: 'https://dummyjson.com/icon/aaliyahh/128',
    email: '',
    gender: '',
  ),
  85: User(
    id: 85,
    firstName: 'Cameron',
    lastName: 'Burke',
    username: 'cameronb',
    image: 'https://dummyjson.com/icon/cameronb/128',
    email: '',
    gender: '',
  ),
  86: User(
    id: 86,
    firstName: 'Nora',
    lastName: 'Mills',
    username: 'noram',
    image: 'https://dummyjson.com/icon/noram/128',
    email: '',
    gender: '',
  ),
  87: User(
    id: 87,
    firstName: 'Hunter',
    lastName: 'Gordon',
    username: 'hunterg',
    image: 'https://dummyjson.com/icon/hunterg/128',
    email: '',
    gender: '',
  ),
  88: User(
    id: 88,
    firstName: 'Aubrey',
    lastName: 'Wagner',
    username: 'aubreyw',
    image: 'https://dummyjson.com/icon/aubreyw/128',
    email: '',
    gender: '',
  ),
  89: User(
    id: 89,
    firstName: 'Brayden',
    lastName: 'Fleming',
    username: 'braydenf',
    image: 'https://dummyjson.com/icon/braydenf/128',
    email: '',
    gender: '',
  ),
  90: User(
    id: 90,
    firstName: 'Scarlett',
    lastName: 'Bowman',
    username: 'scarlettb',
    image: 'https://dummyjson.com/icon/scarlettb/128',
    email: '',
    gender: '',
  ),
  91: User(
    id: 91,
    firstName: 'Levi',
    lastName: 'Hicks',
    username: 'levih',
    image: 'https://dummyjson.com/icon/levih/128',
    email: '',
    gender: '',
  ),
  92: User(
    id: 92,
    firstName: 'Autumn',
    lastName: 'Gomez',
    username: 'autumng',
    image: 'https://dummyjson.com/icon/autumng/128',
    email: '',
    gender: '',
  ),
  93: User(
    id: 93,
    firstName: 'Julian',
    lastName: 'Newton',
    username: 'juliann',
    image: 'https://dummyjson.com/icon/juliann/128',
    email: '',
    gender: '',
  ),
  94: User(
    id: 94,
    firstName: 'Ruby',
    lastName: 'Andrews',
    username: 'rubya',
    image: 'https://dummyjson.com/icon/rubya/128',
    email: '',
    gender: '',
  ),
  95: User(
    id: 95,
    firstName: 'Miles',
    lastName: 'Stevenson',
    username: 'miless',
    image: 'https://dummyjson.com/icon/miless/128',
    email: '',
    gender: '',
  ),
  96: User(
    id: 96,
    firstName: 'Aurora',
    lastName: 'Lawson',
    username: 'auroral',
    image: 'https://dummyjson.com/icon/auroral/128',
    email: '',
    gender: '',
  ),
  97: User(
    id: 97,
    firstName: 'Oscar',
    lastName: 'Powers',
    username: 'oscarp',
    image: 'https://dummyjson.com/icon/oscarp/128',
    email: '',
    gender: '',
  ),
  98: User(
    id: 98,
    firstName: 'Clara',
    lastName: 'Berry',
    username: 'clarab',
    image: 'https://dummyjson.com/icon/clarab/128',
    email: '',
    gender: '',
  ),
  99: User(
    id: 99,
    firstName: 'Gavin',
    lastName: 'Stanley',
    username: 'gavins',
    image: 'https://dummyjson.com/icon/gavins/128',
    email: '',
    gender: '',
  ),
  100: User(
    id: 100,
    firstName: 'Lila',
    lastName: 'Hudson',
    username: 'lilah',
    image: 'https://dummyjson.com/icon/lilah/128',
    email: '',
    gender: '',
  ),
  101: User(
    id: 101,
    firstName: 'Alice',
    lastName: 'Smith',
    username: 'alicej',
    image: 'https://dummyjson.com/icon/alicej/128',
    email: '',
    gender: '',
  ),
  102: User(
    id: 102,
    firstName: 'John',
    lastName: 'Doe',
    username: 'johnd',
    image: 'https://dummyjson.com/icon/johnd/128',
    email: '',
    gender: '',
  ),
  103: User(
    id: 103,
    firstName: 'Emily',
    lastName: 'Brown',
    username: 'emilyt',
    image: 'https://dummyjson.com/icon/emilyt/128',
    email: '',
    gender: '',
  ),
  104: User(
    id: 104,
    firstName: 'Michael',
    lastName: 'Johnson',
    username: 'michaelj',
    image: 'https://dummyjson.com/icon/michaelj/128',
    email: '',
    gender: '',
  ),
  105: User(
    id: 105,
    firstName: 'Emma',
    lastName: 'Wilson',
    username: 'emmac',
    image: 'https://dummyjson.com/icon/emmac/128',
    email: '',
    gender: '',
  ),
  106: User(
    id: 106,
    firstName: 'David',
    lastName: 'Martinez',
    username: 'davidm',
    image: 'https://dummyjson.com/icon/davidm/128',
    email: '',
    gender: '',
  ),
  107: User(
    id: 107,
    firstName: 'Olivia',
    lastName: 'Anderson',
    username: 'oliviah',
    image: 'https://dummyjson.com/icon/oliviah/128',
    email: '',
    gender: '',
  ),
  108: User(
    id: 108,
    firstName: 'James',
    lastName: 'Garcia',
    username: 'jamesg',
    image: 'https://dummyjson.com/icon/jamesg/128',
    email: '',
    gender: '',
  ),
  109: User(
    id: 109,
    firstName: 'Sophia',
    lastName: 'Jones',
    username: 'sophiam',
    image: 'https://dummyjson.com/icon/sophiam/128',
    email: '',
    gender: '',
  ),
  110: User(
    id: 110,
    firstName: 'Daniel',
    lastName: 'Taylor',
    username: 'danielt',
    image: 'https://dummyjson.com/icon/danielt/128',
    email: '',
    gender: '',
  ),
  111: User(
    id: 111,
    firstName: 'Isabella',
    lastName: 'Jackson',
    username: 'isabellaw',
    image: 'https://dummyjson.com/icon/isabellaw/128',
    email: '',
    gender: '',
  ),
  112: User(
    id: 112,
    firstName: 'Alexander',
    lastName: 'Hernandez',
    username: 'alexanderh',
    image: 'https://dummyjson.com/icon/alexanderh/128',
    email: '',
    gender: '',
  ),
  113: User(
    id: 113,
    firstName: 'Mia',
    lastName: 'Miller',
    username: 'miam',
    image: 'https://dummyjson.com/icon/miam/128',
    email: '',
    gender: '',
  ),
  114: User(
    id: 114,
    firstName: 'Ethan',
    lastName: 'Thompson',
    username: 'ethant',
    image: 'https://dummyjson.com/icon/ethant/128',
    email: '',
    gender: '',
  ),
  115: User(
    id: 115,
    firstName: 'Charlotte',
    lastName: 'Davis',
    username: 'charlotteb',
    image: 'https://dummyjson.com/icon/charlotteb/128',
    email: '',
    gender: '',
  ),
  116: User(
    id: 116,
    firstName: 'William',
    lastName: 'Lopez',
    username: 'williaml',
    image: 'https://dummyjson.com/icon/williaml/128',
    email: '',
    gender: '',
  ),
  117: User(
    id: 117,
    firstName: 'Amelia',
    lastName: 'Perez',
    username: 'ameliag',
    image: 'https://dummyjson.com/icon/ameliag/128',
    email: '',
    gender: '',
  ),
  118: User(
    id: 118,
    firstName: 'Benjamin',
    lastName: 'Wilson',
    username: 'benjaminw',
    image: 'https://dummyjson.com/icon/benjaminw/128',
    email: '',
    gender: '',
  ),
  119: User(
    id: 119,
    firstName: 'Liam',
    lastName: 'Gonzalez',
    username: 'liamr',
    image: 'https://dummyjson.com/icon/liamr/128',
    email: '',
    gender: '',
  ),
  120: User(
    id: 120,
    firstName: 'Evelyn',
    lastName: 'Walker',
    username: 'evelynf',
    image: 'https://dummyjson.com/icon/evelynf/128',
    email: '',
    gender: '',
  ),
  121: User(
    id: 121,
    firstName: 'Ava',
    lastName: 'Harris',
    username: 'avahx',
    image: 'https://dummyjson.com/icon/avahx/128',
    email: '',
    gender: '',
  ),
  122: User(
    id: 122,
    firstName: 'Liam',
    lastName: 'Smith',
    username: 'liamt',
    image: 'https://dummyjson.com/icon/liamt/128',
    email: '',
    gender: '',
  ),
  123: User(
    id: 123,
    firstName: 'Harper',
    lastName: 'King',
    username: 'harperb',
    image: 'https://dummyjson.com/icon/harperb/128',
    email: '',
    gender: '',
  ),
  124: User(
    id: 124,
    firstName: 'Noah',
    lastName: 'Lewis',
    username: 'noahl',
    image: 'https://dummyjson.com/icon/noahl/128',
    email: '',
    gender: '',
  ),
  125: User(
    id: 125,
    firstName: 'Logan',
    lastName: 'Lee',
    username: 'loganlx',
    image: 'https://dummyjson.com/icon/loganlx/128',
    email: '',
    gender: '',
  ),
  126: User(
    id: 126,
    firstName: 'Avery',
    lastName: 'Scott',
    username: 'averya',
    image: 'https://dummyjson.com/icon/averya/128',
    email: '',
    gender: '',
  ),
  127: User(
    id: 127,
    firstName: 'Mason',
    lastName: 'Wright',
    username: 'masonw',
    image: 'https://dummyjson.com/icon/masonw/128',
    email: '',
    gender: '',
  ),
  128: User(
    id: 128,
    firstName: 'Grace',
    lastName: 'Green',
    username: 'gracee',
    image: 'https://dummyjson.com/icon/gracee/128',
    email: '',
    gender: '',
  ),
  129: User(
    id: 129,
    firstName: 'Lucas',
    lastName: 'Allen',
    username: 'lucasa',
    image: 'https://dummyjson.com/icon/lucasa/128',
    email: '',
    gender: '',
  ),
  130: User(
    id: 130,
    firstName: 'Chloe',
    lastName: 'Roberts',
    username: 'chloep',
    image: 'https://dummyjson.com/icon/chloep/128',
    email: '',
    gender: '',
  ),
  131: User(
    id: 131,
    firstName: 'Jackson',
    lastName: 'Morales',
    username: 'jacksonm',
    image: 'https://dummyjson.com/icon/jacksonm/128',
    email: '',
    gender: '',
  ),
  132: User(
    id: 132,
    firstName: 'Zoe',
    lastName: 'Bennett',
    username: 'zoec',
    image: 'https://dummyjson.com/icon/zoec/128',
    email: '',
    gender: '',
  ),
  133: User(
    id: 133,
    firstName: 'Carter',
    lastName: 'Rivera',
    username: 'carterr',
    image: 'https://dummyjson.com/icon/carterr/128',
    email: '',
    gender: '',
  ),
  134: User(
    id: 134,
    firstName: 'Nora',
    lastName: 'Russell',
    username: 'noramx',
    image: 'https://dummyjson.com/icon/noramx/128',
    email: '',
    gender: '',
  ),
  135: User(
    id: 135,
    firstName: 'Elijah',
    lastName: 'Cruz',
    username: 'elijahc',
    image: 'https://dummyjson.com/icon/elijahc/128',
    email: '',
    gender: '',
  ),
  136: User(
    id: 136,
    firstName: 'Madison',
    lastName: 'Stewart',
    username: 'madisonk',
    image: 'https://dummyjson.com/icon/madisonk/128',
    email: '',
    gender: '',
  ),
  137: User(
    id: 137,
    firstName: 'Gabriel',
    lastName: 'Bailey',
    username: 'gabrielb',
    image: 'https://dummyjson.com/icon/gabrielb/128',
    email: '',
    gender: '',
  ),
  138: User(
    id: 138,
    firstName: 'Lily',
    lastName: 'Torres',
    username: 'lilyl',
    image: 'https://dummyjson.com/icon/lilyl/128',
    email: '',
    gender: '',
  ),
  139: User(
    id: 139,
    firstName: 'Elijah',
    lastName: 'Hill',
    username: 'elijahh',
    image: 'https://dummyjson.com/icon/elijahh/128',
    email: '',
    gender: '',
  ),
  140: User(
    id: 140,
    firstName: 'Hannah',
    lastName: 'Howard',
    username: 'hannahg',
    image: 'https://dummyjson.com/icon/hannahg/128',
    email: '',
    gender: '',
  ),
  141: User(
    id: 141,
    firstName: 'Owen',
    lastName: 'Sullivan',
    username: 'owens',
    image: 'https://dummyjson.com/icon/owens/128',
    email: '',
    gender: '',
  ),
  142: User(
    id: 142,
    firstName: 'Aria',
    lastName: 'Parker',
    username: 'ariam',
    image: 'https://dummyjson.com/icon/ariam/128',
    email: '',
    gender: '',
  ),
  143: User(
    id: 143,
    firstName: 'Grayson',
    lastName: 'Coleman',
    username: 'graysonc',
    image: 'https://dummyjson.com/icon/graysonc/128',
    email: '',
    gender: '',
  ),
  144: User(
    id: 144,
    firstName: 'Ella',
    lastName: 'Cook',
    username: 'ellar',
    image: 'https://dummyjson.com/icon/ellar/128',
    email: '',
    gender: '',
  ),
  145: User(
    id: 145,
    firstName: 'Luke',
    lastName: 'Cooper',
    username: 'lukec',
    image: 'https://dummyjson.com/icon/lukec/128',
    email: '',
    gender: '',
  ),
  146: User(
    id: 146,
    firstName: 'Leah',
    lastName: 'Hughes',
    username: 'leahp',
    image: 'https://dummyjson.com/icon/leahp/128',
    email: '',
    gender: '',
  ),
  147: User(
    id: 147,
    firstName: 'Henry',
    lastName: 'Turner',
    username: 'henryt',
    image: 'https://dummyjson.com/icon/henryt/128',
    email: '',
    gender: '',
  ),
  148: User(
    id: 148,
    firstName: 'Aurora',
    lastName: 'Barnes',
    username: 'aurorag',
    image: 'https://dummyjson.com/icon/aurorag/128',
    email: '',
    gender: '',
  ),
  149: User(
    id: 149,
    firstName: 'Wyatt',
    lastName: 'Perry',
    username: 'wyattp',
    image: 'https://dummyjson.com/icon/wyattp/128',
    email: '',
    gender: '',
  ),
  150: User(
    id: 150,
    firstName: 'Stella',
    lastName: 'Morris',
    username: 'stellas',
    image: 'https://dummyjson.com/icon/stellas/128',
    email: '',
    gender: '',
  ),
  151: User(
    id: 151,
    firstName: 'Nathan',
    lastName: 'Reed',
    username: 'nathanr',
    image: 'https://dummyjson.com/icon/nathanr/128',
    email: '',
    gender: '',
  ),
  152: User(
    id: 152,
    firstName: 'Paisley',
    lastName: 'Bell',
    username: 'paisleyf',
    image: 'https://dummyjson.com/icon/paisleyf/128',
    email: '',
    gender: '',
  ),
  153: User(
    id: 153,
    firstName: 'Christian',
    lastName: 'Perez',
    username: 'christianp',
    image: 'https://dummyjson.com/icon/christianp/128',
    email: '',
    gender: '',
  ),
  154: User(
    id: 154,
    firstName: 'Bella',
    lastName: 'Gonzalez',
    username: 'bellaa',
    image: 'https://dummyjson.com/icon/bellaa/128',
    email: '',
    gender: '',
  ),
  155: User(
    id: 155,
    firstName: 'Nicholas',
    lastName: 'Edwards',
    username: 'nicholase',
    image: 'https://dummyjson.com/icon/nicholase/128',
    email: '',
    gender: '',
  ),
  156: User(
    id: 156,
    firstName: 'Mila',
    lastName: 'Hernandez',
    username: 'milam',
    image: 'https://dummyjson.com/icon/milam/128',
    email: '',
    gender: '',
  ),
  157: User(
    id: 157,
    firstName: 'Aaron',
    lastName: 'Cook',
    username: 'aaronc',
    image: 'https://dummyjson.com/icon/aaronc/128',
    email: '',
    gender: '',
  ),
  158: User(
    id: 158,
    firstName: 'Aubrey',
    lastName: 'Gutierrez',
    username: 'aubreyb',
    image: 'https://dummyjson.com/icon/aubreyb/128',
    email: '',
    gender: '',
  ),
  159: User(
    id: 159,
    firstName: 'Eli',
    lastName: 'Ward',
    username: 'eliw',
    image: 'https://dummyjson.com/icon/eliw/128',
    email: '',
    gender: '',
  ),
  160: User(
    id: 160,
    firstName: 'Claire',
    lastName: 'Foster',
    username: 'claires',
    image: 'https://dummyjson.com/icon/claires/128',
    email: '',
    gender: '',
  ),
  161: User(
    id: 161,
    firstName: 'James',
    lastName: 'Gonzales',
    username: 'jamesgx',
    image: 'https://dummyjson.com/icon/jamesgx/128',
    email: '',
    gender: '',
  ),
  162: User(
    id: 162,
    firstName: 'Mateo',
    lastName: 'Bennett',
    username: 'mateob',
    image: 'https://dummyjson.com/icon/mateob/128',
    email: '',
    gender: '',
  ),
  163: User(
    id: 163,
    firstName: 'Julian',
    lastName: 'James',
    username: 'julianj',
    image: 'https://dummyjson.com/icon/julianj/128',
    email: '',
    gender: '',
  ),
  164: User(
    id: 164,
    firstName: 'Addison',
    lastName: 'Ward',
    username: 'addisonf',
    image: 'https://dummyjson.com/icon/addisonf/128',
    email: '',
    gender: '',
  ),
  165: User(
    id: 165,
    firstName: 'Leo',
    lastName: 'Rivera',
    username: 'leor',
    image: 'https://dummyjson.com/icon/leor/128',
    email: '',
    gender: '',
  ),
  166: User(
    id: 166,
    firstName: 'Elena',
    lastName: 'Long',
    username: 'elenam',
    image: 'https://dummyjson.com/icon/elenam/128',
    email: '',
    gender: '',
  ),
  167: User(
    id: 167,
    firstName: 'Evan',
    lastName: 'Wright',
    username: 'evanw',
    image: 'https://dummyjson.com/icon/evanw/128',
    email: '',
    gender: '',
  ),
  168: User(
    id: 168,
    firstName: 'Luna',
    lastName: 'Perez',
    username: 'lunah',
    image: 'https://dummyjson.com/icon/lunah/128',
    email: '',
    gender: '',
  ),
  169: User(
    id: 169,
    firstName: 'Jaxon',
    lastName: 'Barnes',
    username: 'jaxonb',
    image: 'https://dummyjson.com/icon/jaxonb/128',
    email: '',
    gender: '',
  ),
  170: User(
    id: 170,
    firstName: 'Penelope',
    lastName: 'King',
    username: 'penelopet',
    image: 'https://dummyjson.com/icon/penelopet/128',
    email: '',
    gender: '',
  ),
  171: User(
    id: 171,
    firstName: 'Connor',
    lastName: 'Baker',
    username: 'connorb',
    image: 'https://dummyjson.com/icon/connorb/128',
    email: '',
    gender: '',
  ),
  172: User(
    id: 172,
    firstName: 'Ariana',
    lastName: 'Ross',
    username: 'arianaw',
    image: 'https://dummyjson.com/icon/arianaw/128',
    email: '',
    gender: '',
  ),
  173: User(
    id: 173,
    firstName: 'Asher',
    lastName: 'Scott',
    username: 'ashers',
    image: 'https://dummyjson.com/icon/ashers/128',
    email: '',
    gender: '',
  ),
  174: User(
    id: 174,
    firstName: 'Sadie',
    lastName: 'Morales',
    username: 'sadiep',
    image: 'https://dummyjson.com/icon/sadiep/128',
    email: '',
    gender: '',
  ),
  175: User(
    id: 175,
    firstName: 'Gabriel',
    lastName: 'Mitchell',
    username: 'gabrielm',
    image: 'https://dummyjson.com/icon/gabrielm/128',
    email: '',
    gender: '',
  ),
  176: User(
    id: 176,
    firstName: 'Aaliyah',
    lastName: 'Martinez',
    username: 'aaliyaha',
    image: 'https://dummyjson.com/icon/aaliyaha/128',
    email: '',
    gender: '',
  ),
  177: User(
    id: 177,
    firstName: 'Xavier',
    lastName: 'Wright',
    username: 'xavierw',
    image: 'https://dummyjson.com/icon/xavierw/128',
    email: '',
    gender: '',
  ),
  178: User(
    id: 178,
    firstName: 'Savannah',
    lastName: 'Gomez',
    username: 'savannahe',
    image: 'https://dummyjson.com/icon/savannahe/128',
    email: '',
    gender: '',
  ),
  179: User(
    id: 179,
    firstName: 'Tyler',
    lastName: 'Davis',
    username: 'tylerd',
    image: 'https://dummyjson.com/icon/tylerd/128',
    email: '',
    gender: '',
  ),
  180: User(
    id: 180,
    firstName: 'Aurora',
    lastName: 'Rodriguez',
    username: 'auroran',
    image: 'https://dummyjson.com/icon/auroran/128',
    email: '',
    gender: '',
  ),
  181: User(
    id: 181,
    firstName: 'Brandon',
    lastName: 'Collins',
    username: 'brandonc',
    image: 'https://dummyjson.com/icon/brandonc/128',
    email: '',
    gender: '',
  ),
  182: User(
    id: 182,
    firstName: 'Ellie',
    lastName: 'Stewart',
    username: 'ellieh',
    image: 'https://dummyjson.com/icon/ellieh/128',
    email: '',
    gender: '',
  ),
  183: User(
    id: 183,
    firstName: 'Cameron',
    lastName: 'Perez',
    username: 'cameronp',
    image: 'https://dummyjson.com/icon/cameronp/128',
    email: '',
    gender: '',
  ),
  184: User(
    id: 184,
    firstName: 'Natalie',
    lastName: 'Price',
    username: 'nataliehx',
    image: 'https://dummyjson.com/icon/nataliehx/128',
    email: '',
    gender: '',
  ),
  185: User(
    id: 185,
    firstName: 'Henry',
    lastName: 'Adams',
    username: 'henrya',
    image: 'https://dummyjson.com/icon/henrya/128',
    email: '',
    gender: '',
  ),
  186: User(
    id: 186,
    firstName: 'Harper',
    lastName: 'Garcia',
    username: 'harperbx',
    image: 'https://dummyjson.com/icon/harperbx/128',
    email: '',
    gender: '',
  ),
  187: User(
    id: 187,
    firstName: 'Zachary',
    lastName: 'Lee',
    username: 'zacharyl',
    image: 'https://dummyjson.com/icon/zacharyl/128',
    email: '',
    gender: '',
  ),
  188: User(
    id: 188,
    firstName: 'Aria',
    lastName: 'Flores',
    username: 'ariamx',
    image: 'https://dummyjson.com/icon/ariamx/128',
    email: '',
    gender: '',
  ),
  189: User(
    id: 189,
    firstName: 'Tristan',
    lastName: 'Scott',
    username: 'tristans',
    image: 'https://dummyjson.com/icon/tristans/128',
    email: '',
    gender: '',
  ),
  190: User(
    id: 190,
    firstName: 'Leah',
    lastName: 'Gutierrez',
    username: 'leahw',
    image: 'https://dummyjson.com/icon/leahw/128',
    email: '',
    gender: '',
  ),
  191: User(
    id: 191,
    firstName: 'Layla',
    lastName: 'Young',
    username: 'laylab',
    image: 'https://dummyjson.com/icon/laylab/128',
    email: '',
    gender: '',
  ),
  192: User(
    id: 192,
    firstName: 'Nolan',
    lastName: 'Gonzalez',
    username: 'nolang',
    image: 'https://dummyjson.com/icon/nolang/128',
    email: '',
    gender: '',
  ),
  193: User(
    id: 193,
    firstName: 'Hazel',
    lastName: 'Evans',
    username: 'hazelc',
    image: 'https://dummyjson.com/icon/hazelc/128',
    email: '',
    gender: '',
  ),
  194: User(
    id: 194,
    firstName: 'Brayden',
    lastName: 'Hill',
    username: 'braydenh',
    image: 'https://dummyjson.com/icon/braydenh/128',
    email: '',
    gender: '',
  ),
  195: User(
    id: 195,
    firstName: 'Violet',
    lastName: 'Roberts',
    username: 'violeta',
    image: 'https://dummyjson.com/icon/violeta/128',
    email: '',
    gender: '',
  ),
  196: User(
    id: 196,
    firstName: 'Lucas',
    lastName: 'Ramirez',
    username: 'lucasr',
    image: 'https://dummyjson.com/icon/lucasr/128',
    email: '',
    gender: '',
  ),
  197: User(
    id: 197,
    firstName: 'Eleanor',
    lastName: 'Collins',
    username: 'eleanorw',
    image: 'https://dummyjson.com/icon/eleanorw/128',
    email: '',
    gender: '',
  ),
  198: User(
    id: 198,
    firstName: 'Max',
    lastName: 'Parker',
    username: 'maxp',
    image: 'https://dummyjson.com/icon/maxp/128',
    email: '',
    gender: '',
  ),
  199: User(
    id: 199,
    firstName: 'Vivian',
    lastName: 'Carter',
    username: 'viviang',
    image: 'https://dummyjson.com/icon/viviang/128',
    email: '',
    gender: '',
  ),
  200: User(
    id: 200,
    firstName: 'Adrian',
    lastName: 'Flores',
    username: 'adrianf',
    image: 'https://dummyjson.com/icon/adrianf/128',
    email: '',
    gender: '',
  ),
  201: User(
    id: 201,
    firstName: 'Maya',
    lastName: 'Reed',
    username: 'mayah',
    image: 'https://dummyjson.com/icon/mayah/128',
    email: '',
    gender: '',
  ),
  202: User(
    id: 202,
    firstName: 'Caleb',
    lastName: 'Nelson',
    username: 'calebn',
    image: 'https://dummyjson.com/icon/calebn/128',
    email: '',
    gender: '',
  ),
  203: User(
    id: 203,
    firstName: 'Nova',
    lastName: 'Cooper',
    username: 'novab',
    image: 'https://dummyjson.com/icon/novab/128',
    email: '',
    gender: '',
  ),
  204: User(
    id: 204,
    firstName: 'Mateo',
    lastName: 'Perez',
    username: 'mateop',
    image: 'https://dummyjson.com/icon/mateop/128',
    email: '',
    gender: '',
  ),
  205: User(
    id: 205,
    firstName: 'Aubrey',
    lastName: 'Garcia',
    username: 'aubreyg',
    image: 'https://dummyjson.com/icon/aubreyg/128',
    email: '',
    gender: '',
  ),
  206: User(
    id: 206,
    firstName: 'Elena',
    lastName: 'Baker',
    username: 'elenab',
    image: 'https://dummyjson.com/icon/elenab/128',
    email: '',
    gender: '',
  ),
  207: User(
    id: 207,
    firstName: 'Jace',
    lastName: 'Smith',
    username: 'jaces',
    image: 'https://dummyjson.com/icon/jaces/128',
    email: '',
    gender: '',
  ),
  208: User(
    id: 208,
    firstName: 'Samantha',
    lastName: 'Martinez',
    username: 'samanthal',
    image: 'https://dummyjson.com/icon/samanthal/128',
    email: '',
    gender: '',
  ),
};
